[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "brutasse"
version = "0.0.1"
dependencies = [
    "progressbar2",
    "termcolor",
    "aiohttp",
    "asyncssh",
    "sqlalchemy",
    "pyyaml",
    "pyasn1",
    "pyasn1-modules",
]